from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from fastapi.responses import JSONResponse
import requests
import os

app = FastAPI(
    title="Agentforce API Wrapper",
    description="A REST interface that wraps Salesforce Agentforce. Send a message to the Apex REST endpoint and receive an AI-generated response.",
    version="1.0.0"
)

class Message(BaseModel):
    message: str

@app.get("/")
def root():
    return {"message": "Agentforce connector is live."}

@app.post(
    "/agentforce",
    summary="Send message to Agentforce",
    description="Send a natural language message to Salesforce's Agentforce Apex REST endpoint. The response will be generated by the Agentforce AI agent."
)
def call_agentforce(msg: Message):
    token = os.getenv("SF_ACCESS_TOKEN")
    instance_url = os.getenv("SF_INSTANCE_URL")

    if not token or not instance_url:
        raise HTTPException(status_code=500, detail="Salesforce credentials not configured.")

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }

    try:
        response = requests.post(
            f"{instance_url}/services/apexrest/agentforce",
            headers=headers,
            json={"message": msg.message}
        )
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/.well-known/ai-plugin.json", include_in_schema=False)
def plugin_manifest():
    return JSONResponse({
        "schema_version": "v1",
        "name_for_human": "Agentforce Connector",
        "name_for_model": "agentforce_connector",
        "description_for_model": "Send natural language CRM requests to Salesforce's Agentforce.",
        "auth": { "type": "none" },
        "api": {
            "type": "openapi",
            "url": "https://agentforce-connector-1148de6e18d0.herokuapp.com/openapi.json",
            "is_user_authenticated": False
        },
        "logo_url": "https://your-logo-url.com/logo.png",
        "contact_email": "you@example.com",
        "legal_info_url": "https://your-legal-page.com"
    })
